// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proxy_account_contract.proto
// </auto-generated>
// Original file comments:
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.ProxyAccountContract {

  #region Events
  public partial class ProxyAccountCreated : aelf::IEvent<ProxyAccountCreated>
  {
    public global::System.Collections.Generic.IEnumerable<ProxyAccountCreated> GetIndexed()
    {
      return new List<ProxyAccountCreated>
      {
      };
    }

    public ProxyAccountCreated GetNonIndexed()
    {
      return new ProxyAccountCreated
      {
        ManagementAddresses = ManagementAddresses,
        CreateChainId = CreateChainId,
        ProxyAccountHash = ProxyAccountHash,
        ProxyAccountAddress = ProxyAccountAddress,
      };
    }
  }

  public partial class ProxyAccountManagementAddressAdded : aelf::IEvent<ProxyAccountManagementAddressAdded>
  {
    public global::System.Collections.Generic.IEnumerable<ProxyAccountManagementAddressAdded> GetIndexed()
    {
      return new List<ProxyAccountManagementAddressAdded>
      {
      };
    }

    public ProxyAccountManagementAddressAdded GetNonIndexed()
    {
      return new ProxyAccountManagementAddressAdded
      {
        ManagementAddress = ManagementAddress,
        ProxyAccountHash = ProxyAccountHash,
        ProxyAccountAddress = ProxyAccountAddress,
      };
    }
  }

  public partial class ProxyAccountManagementAddressRemoved : aelf::IEvent<ProxyAccountManagementAddressRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<ProxyAccountManagementAddressRemoved> GetIndexed()
    {
      return new List<ProxyAccountManagementAddressRemoved>
      {
      };
    }

    public ProxyAccountManagementAddressRemoved GetNonIndexed()
    {
      return new ProxyAccountManagementAddressRemoved
      {
        ManagementAddress = ManagementAddress,
        ProxyAccountHash = ProxyAccountHash,
        ProxyAccountAddress = ProxyAccountAddress,
      };
    }
  }

  public partial class ProxyAccountManagementAddressReset : aelf::IEvent<ProxyAccountManagementAddressReset>
  {
    public global::System.Collections.Generic.IEnumerable<ProxyAccountManagementAddressReset> GetIndexed()
    {
      return new List<ProxyAccountManagementAddressReset>
      {
      };
    }

    public ProxyAccountManagementAddressReset GetNonIndexed()
    {
      return new ProxyAccountManagementAddressReset
      {
        ManagementAddresses = ManagementAddresses,
        ProxyAccountHash = ProxyAccountHash,
        ProxyAccountAddress = ProxyAccountAddress,
      };
    }
  }

  public partial class BatchTokenCreated : aelf::IEvent<BatchTokenCreated>
  {
    public global::System.Collections.Generic.IEnumerable<BatchTokenCreated> GetIndexed()
    {
      return new List<BatchTokenCreated>
      {
      };
    }

    public BatchTokenCreated GetNonIndexed()
    {
      return new BatchTokenCreated
      {
        Address = Address,
        ExternalInfoDetails = ExternalInfoDetails,
      };
    }
  }

  #endregion
  /// <summary>
  /// the contract definition: a gRPC service definition.
  /// </summary>
  public static partial class ProxyAccountContractContainer
  {
    static readonly string __ServiceName = "ProxyAccountContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.SetProxyAccountContractsInput> __Marshaller_SetProxyAccountContractsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.SetProxyAccountContractsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.CreateInput> __Marshaller_CreateInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.CreateInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.AddManagementAddressInput> __Marshaller_AddManagementAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.AddManagementAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.RemoveManagementAddressInput> __Marshaller_RemoveManagementAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.RemoveManagementAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.ResetManagementAddressInput> __Marshaller_ResetManagementAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.ResetManagementAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.ForwardCallInput> __Marshaller_ForwardCallInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.ForwardCallInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.ValidateProxyAccountExistsInput> __Marshaller_ValidateProxyAccountExistsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.ValidateProxyAccountExistsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.CrossChainSyncProxyAccountInput> __Marshaller_CrossChainSyncProxyAccountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.CrossChainSyncProxyAccountInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.BatchCreateInput> __Marshaller_BatchCreateInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.BatchCreateInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.BatchCreateTokenInput> __Marshaller_BatchCreateTokenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.BatchCreateTokenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.GetProxyAccountAddressInput> __Marshaller_GetProxyAccountAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.GetProxyAccountAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.ProxyAccount> __Marshaller_ProxyAccount = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.ProxyAccount.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Contracts.ProxyAccountContract.GetProxyAccountHashInput> __Marshaller_GetProxyAccountHashInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Contracts.ProxyAccountContract.GetProxyAccountHashInput.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.SetProxyAccountContractsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetProxyAccountContracts = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.SetProxyAccountContractsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetProxyAccountContracts",
        __Marshaller_SetProxyAccountContractsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxManagementAddressCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxManagementAddressCount",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.CreateInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Create = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.CreateInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Create",
        __Marshaller_CreateInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.AddManagementAddressInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddManagementAddress = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.AddManagementAddressInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddManagementAddress",
        __Marshaller_AddManagementAddressInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.RemoveManagementAddressInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveManagementAddress = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.RemoveManagementAddressInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveManagementAddress",
        __Marshaller_RemoveManagementAddressInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.ResetManagementAddressInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ResetManagementAddress = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.ResetManagementAddressInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ResetManagementAddress",
        __Marshaller_ResetManagementAddressInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.ForwardCallInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ForwardCall = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.ForwardCallInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ForwardCall",
        __Marshaller_ForwardCallInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.ValidateProxyAccountExistsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ValidateProxyAccountExists = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.ValidateProxyAccountExistsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ValidateProxyAccountExists",
        __Marshaller_ValidateProxyAccountExistsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.CrossChainSyncProxyAccountInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CrossChainSyncProxyAccount = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.CrossChainSyncProxyAccountInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CrossChainSyncProxyAccount",
        __Marshaller_CrossChainSyncProxyAccountInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.BatchCreateInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_BatchCreateNFT = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.BatchCreateInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "BatchCreateNFT",
        __Marshaller_BatchCreateInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.BatchCreateTokenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_BatchCreateToken = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.BatchCreateTokenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "BatchCreateToken",
        __Marshaller_BatchCreateTokenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxBatchCreateTokenCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxBatchCreateTokenCount",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetTokenContractAddress = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTokenContractAddress",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetMaxManagementAddressCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMaxManagementAddressCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.GetProxyAccountAddressInput, global::AElf.Types.Address> __Method_GetProxyAccountAddress = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.GetProxyAccountAddressInput, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetProxyAccountAddress",
        __Marshaller_GetProxyAccountAddressInput,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.ProxyAccountContract.ProxyAccount> __Method_GetProxyAccountByHash = new aelf::Method<global::AElf.Types.Hash, global::AElf.Contracts.ProxyAccountContract.ProxyAccount>(
        aelf::MethodType.View,
        __ServiceName,
        "GetProxyAccountByHash",
        __Marshaller_aelf_Hash,
        __Marshaller_ProxyAccount);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.ProxyAccountContract.ProxyAccount> __Method_GetProxyAccountByProxyAccountAddress = new aelf::Method<global::AElf.Types.Address, global::AElf.Contracts.ProxyAccountContract.ProxyAccount>(
        aelf::MethodType.View,
        __ServiceName,
        "GetProxyAccountByProxyAccountAddress",
        __Marshaller_aelf_Address,
        __Marshaller_ProxyAccount);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetCurrentCounter = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCurrentCounter",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Contracts.ProxyAccountContract.GetProxyAccountHashInput, global::AElf.Types.Hash> __Method_GetProxyAccountHash = new aelf::Method<global::AElf.Contracts.ProxyAccountContract.GetProxyAccountHashInput, global::AElf.Types.Hash>(
        aelf::MethodType.View,
        __ServiceName,
        "GetProxyAccountHash",
        __Marshaller_GetProxyAccountHashInput,
        __Marshaller_aelf_Hash);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetMaxBatchCreateTokenCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMaxBatchCreateTokenCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetTokenContractAddress = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTokenContractAddress",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.ProxyAccountContract.ProxyAccountContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::AElf.Contracts.ProxyAccountContract.ProxyAccountContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of ProxyAccountContract</summary>
    // public abstract partial class ProxyAccountContractBase : AElf.Sdk.CSharp.CSharpSmartContract<AElf.Contracts.ProxyAccountContract.ProxyAccountContractState>
    // {
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Initialize(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetProxyAccountContracts(global::AElf.Contracts.ProxyAccountContract.SetProxyAccountContractsInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetAdmin(global::AElf.Types.Address input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetMaxManagementAddressCount(global::Google.Protobuf.WellKnownTypes.Int32Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Create(global::AElf.Contracts.ProxyAccountContract.CreateInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddManagementAddress(global::AElf.Contracts.ProxyAccountContract.AddManagementAddressInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveManagementAddress(global::AElf.Contracts.ProxyAccountContract.RemoveManagementAddressInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ResetManagementAddress(global::AElf.Contracts.ProxyAccountContract.ResetManagementAddressInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ForwardCall(global::AElf.Contracts.ProxyAccountContract.ForwardCallInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ValidateProxyAccountExists(global::AElf.Contracts.ProxyAccountContract.ValidateProxyAccountExistsInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty CrossChainSyncProxyAccount(global::AElf.Contracts.ProxyAccountContract.CrossChainSyncProxyAccountInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty BatchCreateNFT(global::AElf.Contracts.ProxyAccountContract.BatchCreateInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty BatchCreateToken(global::AElf.Contracts.ProxyAccountContract.BatchCreateTokenInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetMaxBatchCreateTokenCount(global::Google.Protobuf.WellKnownTypes.Int32Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetTokenContractAddress(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Address GetAdmin(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int32Value GetMaxManagementAddressCount(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Address GetProxyAccountAddress(global::AElf.Contracts.ProxyAccountContract.GetProxyAccountAddressInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Contracts.ProxyAccountContract.ProxyAccount GetProxyAccountByHash(global::AElf.Types.Hash input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Contracts.ProxyAccountContract.ProxyAccount GetProxyAccountByProxyAccountAddress(global::AElf.Types.Address input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int64Value GetCurrentCounter(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Hash GetProxyAccountHash(global::AElf.Contracts.ProxyAccountContract.GetProxyAccountHashInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int32Value GetMaxBatchCreateTokenCount(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Address GetTokenContractAddress(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    // }
    //
    // public static aelf::ServerServiceDefinition BindService(ProxyAccountContractBase serviceImpl)
    // {
    //   return aelf::ServerServiceDefinition.CreateBuilder()
    //       .AddDescriptors(Descriptors)
    //       .AddMethod(__Method_Initialize, serviceImpl.Initialize)
    //       .AddMethod(__Method_SetProxyAccountContracts, serviceImpl.SetProxyAccountContracts)
    //       .AddMethod(__Method_SetAdmin, serviceImpl.SetAdmin)
    //       .AddMethod(__Method_SetMaxManagementAddressCount, serviceImpl.SetMaxManagementAddressCount)
    //       .AddMethod(__Method_Create, serviceImpl.Create)
    //       .AddMethod(__Method_AddManagementAddress, serviceImpl.AddManagementAddress)
    //       .AddMethod(__Method_RemoveManagementAddress, serviceImpl.RemoveManagementAddress)
    //       .AddMethod(__Method_ResetManagementAddress, serviceImpl.ResetManagementAddress)
    //       .AddMethod(__Method_ForwardCall, serviceImpl.ForwardCall)
    //       .AddMethod(__Method_ValidateProxyAccountExists, serviceImpl.ValidateProxyAccountExists)
    //       .AddMethod(__Method_CrossChainSyncProxyAccount, serviceImpl.CrossChainSyncProxyAccount)
    //       .AddMethod(__Method_BatchCreateNFT, serviceImpl.BatchCreateNFT)
    //       .AddMethod(__Method_BatchCreateToken, serviceImpl.BatchCreateToken)
    //       .AddMethod(__Method_SetMaxBatchCreateTokenCount, serviceImpl.SetMaxBatchCreateTokenCount)
    //       .AddMethod(__Method_SetTokenContractAddress, serviceImpl.SetTokenContractAddress)
    //       .AddMethod(__Method_GetAdmin, serviceImpl.GetAdmin)
    //       .AddMethod(__Method_GetMaxManagementAddressCount, serviceImpl.GetMaxManagementAddressCount)
    //       .AddMethod(__Method_GetProxyAccountAddress, serviceImpl.GetProxyAccountAddress)
    //       .AddMethod(__Method_GetProxyAccountByHash, serviceImpl.GetProxyAccountByHash)
    //       .AddMethod(__Method_GetProxyAccountByProxyAccountAddress, serviceImpl.GetProxyAccountByProxyAccountAddress)
    //       .AddMethod(__Method_GetCurrentCounter, serviceImpl.GetCurrentCounter)
    //       .AddMethod(__Method_GetProxyAccountHash, serviceImpl.GetProxyAccountHash)
    //       .AddMethod(__Method_GetMaxBatchCreateTokenCount, serviceImpl.GetMaxBatchCreateTokenCount)
    //       .AddMethod(__Method_GetTokenContractAddress, serviceImpl.GetTokenContractAddress).Build();
    // }

  }
}
#endregion

